version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "gomod"
    directory: "/cicd-pipeline/docker-builds"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/cicd-pipeline/docker-builds"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/multi-cloud-infra/terraform-aws"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "terraform"
    directory: "/multi-cloud-infra/terraform-gcp"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "terraform"
    directory: "/multi-cloud-infra/terraform-azure"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/cloud-cost-optimization"
    schedule:
      interval: "weekly"
